// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P04Sklep.API.Data;

#nullable disable

namespace P04Sklep.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230131121704_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("P05Sklep.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 22,
                            Color = "orange",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            ImgUrl = "https://loremflickr.com/320/240?lock=2101005094",
                            Title = "Sleek Cotton Ball"
                        },
                        new
                        {
                            Id = 23,
                            Color = "grey",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            ImgUrl = "https://loremflickr.com/320/240?lock=1239332566",
                            Title = "Incredible Rubber Keyboard"
                        },
                        new
                        {
                            Id = 24,
                            Color = "yellow",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            ImgUrl = "https://loremflickr.com/320/240?lock=1381805223",
                            Title = "Ergonomic Fresh Fish"
                        },
                        new
                        {
                            Id = 25,
                            Color = "silver",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            ImgUrl = "https://loremflickr.com/320/240?lock=2130438457",
                            Title = "Refined Rubber Pizza"
                        },
                        new
                        {
                            Id = 26,
                            Color = "plum",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            ImgUrl = "https://loremflickr.com/320/240?lock=630231208",
                            Title = "Handcrafted Frozen Fish"
                        },
                        new
                        {
                            Id = 27,
                            Color = "blue",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            ImgUrl = "https://loremflickr.com/320/240?lock=1252756713",
                            Title = "Handmade Wooden Car"
                        },
                        new
                        {
                            Id = 28,
                            Color = "white",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            ImgUrl = "https://loremflickr.com/320/240?lock=1082487822",
                            Title = "Intelligent Steel Keyboard"
                        },
                        new
                        {
                            Id = 29,
                            Color = "red",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            ImgUrl = "https://loremflickr.com/320/240?lock=182736563",
                            Title = "Gorgeous Cotton Hat"
                        },
                        new
                        {
                            Id = 30,
                            Color = "fuchsia",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            ImgUrl = "https://loremflickr.com/320/240?lock=1508701604",
                            Title = "Handcrafted Concrete Pants"
                        },
                        new
                        {
                            Id = 31,
                            Color = "plum",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            ImgUrl = "https://loremflickr.com/320/240?lock=851157842",
                            Title = "Unbranded Plastic Sausages"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
